apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster

nodes:
- role: control-plane
  kubeadmConfigPatches: # for using ingress
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "ingress-ready=true"

  extraPortMappings:
  - containerPort: 80
    hostPort: 80
    protocol: TCP
  - containerPort: 31593 # for NodePort
    hostPort: 31593
    protocol: TCP


- role: worker
  extraMounts:
    - hostPath: ./hostroot_in_node
      containerPath: /hostroot