apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster

nodes:
- role: control-plane # configuration for control-plane node

- role: worker # configuration for worker1 node
  extraMounts:
    - hostPath: ./hostroot_in_node
      containerPath: /hostroot
    - hostPath: ./pvc
      containerPath: /var/local-path-provisioner
- role: worker # configuration for worker2 node
  extraMounts:
    - hostPath: ./hostroot_in_node
      containerPath: /hostroot
    - hostPath: ./pvc
      containerPath: /var/local-path-provisioner
- role: worker # configuration for worker3 node
  extraMounts:
    - hostPath: ./hostroot_in_node
      containerPath: /hostroot
    - hostPath: ./pvc
      containerPath: /var/local-path-provisioner