apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster
name: my-cluster

nodes:
- role: control-plane
  kubeadmConfigPatches: # for using ingress
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "ingress-ready=true"

  extraPortMappings:
  - containerPort: 80 # for ingress
    hostPort: 80
    protocol: TCP
  - containerPort: 30001 # for NodePort jenkins
    hostPort: 30001
    protocol: TCP


- role: worker
  extraMounts:
    - hostPath: ./hostroot_in_node
      containerPath: /hostroot